name: Periodic check

on:
  schedule:
    # every day at 20.00
    - cron:  '0 20 1 * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check if heroku is online
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://limitless-bayou-39628.herokuapp.com/health
        follow-redirect: false
        retry-delay: 5s
        retry-all: false